# Generated by Django 5.1.7 on 2025-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
