# Generated by Django 5.1.7 on 2025-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
